---
driver:
  name: vagrant
  customize:
    memory: 1024 

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04

suites:
  - name: pydotorg-es
    roles_path: ../../roles
    data_bag_path: ../../data_bags
    run_list: 
      - role[base]
      - role[pydotorg-prod-es]
    attributes:
  - name: pydotorg
    roles_path: ../../roles/
    data_bag_path: ../../data_bags/
    run_list:
      - role[base]
      - role[pydotorg-prod]
